# permissions for end users to view cruds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crud-viewer-role
rules:
- apiGroups:
  - api.crudgen.org
  resources:
  - cruds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.crudgen.org
  resources:
  - cruds/status
  verbs:
  - get
