
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - api.crudgen.org
  resources:
  - cruds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.crudgen.org
  resources:
  - cruds/status
  verbs:
  - get
  - patch
  - update
